### ISSUE TITLE
IP differes between script and real IP (from router)

### ISSUE THREAD

**Issue by jagjordi** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#105]
The map in home assistant stopped working some days ago.
When trying you troubleshoot I found that the IP of the vacuum cleaner has changed ( as seen in the router, and also by pinging it). However when I run the token extractor it seems that the IP there is still the old one.
Neither of the IPs for `xiaomi_vaccum_host` option in ymal config makes it work.
What should I do?
![image](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/assets/14058667/a3376702-50d8-4c13-90af-7f533efa69f7)
![image](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/assets/14058667/ed46ea7d-a74a-496d-85a1-45853e8de8c7)

**Comment by PiotrMachowski** [comment]
Token Extractor retrieves data from Xiaomi Cloud. Try checking IP in Xiaomi Home app. The easiest way to adjust it would be to set a static DHCP address in the router and reboot the vacuum.

**Comment by jagjordi** [comment]
Does this integration work if we use the RoboRock app?
I have been using it for about 6 months with the roborock app and it has worked, but 1 or 2 weeks ago it suddenly stopped working

**Comment by PiotrMachowski** [comment]
No, it doesn't
