### ISSUE TITLE
Possibility to use Roborock App too?

### ISSUE THREAD

**Issue by u20p17** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#11]
Hi,
at the moment the tool works perfektly with the Xiaomi Home App. If the roborock is connected via the Roborock app would it also be possible to get the token somehow? Would be a great addon for this tool!

BR

**Comment by PiotrMachowski** [comment]
Hi,

Roborock app uses Tuya cloud, so extracting a token from it is a whole different project. You might try to contact @89jd to add such a feature
