### ISSUE TITLE
Detects one device only

### ISSUE THREAD

**Issue by mortenperiksen** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#112]
Hi

I have two devices connected to Roborocks under the same account:
- S5 Max
- S8

However, only the S5 Max is discovered by token_extractor.exe.

Any idea why?

Thanks in advance,
Morten

**Comment by PiotrMachowski** [comment]
Are they both available in Xiaomi Home?

**Comment by mortenperiksen** [comment]
I’m using the Roborock APP, but yes they are both in the app. 
Sendt fra min iPhone

> Den 24. feb. 2024 kl. 18.08 skrev Piotr Machowski ***@***.***>:
> 
> Xiaomi Home

**Comment by PiotrMachowski** [comment]
Well, this extractor doesn't work with Roborock app - it uses a different cloud
