### ISSUE TITLE
SyntaxError: invalid syntax on return line 152

### ISSUE THREAD

**Issue by MrVinceZ** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#12]
Hello !

I want to use this script on my Debian 9 and this is what happened when I run this 
`python token_extractor.py

File "token_extractor.py", line 152
return f"Android-7.1.1-1.0.0-ONEPLUS A3010-136-{agent_id} APP/xiaomi.smarthome APPV/62830"
SyntaxError: invalid syntax`

Can you help me ? Thank you

**Comment by PiotrMachowski** [comment]
Which version of python do you have?

**Comment by MrVinceZ** [comment]
3.5  

Problem resolve after an update to Python 3.8

Thank you
