### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by 4q1** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#121]
**"You will need to provide Xiaomi Home credentials (not ones from Roborock app):"**

I have a roborock machine, with a roborock app and roborock login.  I don't have any  Xiaomi Home credentials, nor any way to get them that I can see.  I tried the Roborock credentials, but of course they do not work.  The instructions don't cover this. 
What should I do?

**Comment by PiotrMachowski** [comment]
You should not use Tokens Extractor, it doesn't work with Roborock app. For what do you need it?

**Comment by PiotrMachowski** [comment]
This video is 4 years old, it is ages in HA world. Now you just can use [a built-in Roborock integration](https://www.home-assistant.io/integrations/roborock/)
