### ISSUE TITLE
Tool to validate token is valid?

### ISSUE THREAD

**Issue by nickdos** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#13]
I'm trying to debug an issue with my Robot vacuum, where it is showing as unavailable in HA. I've reset the Wifi on it and ran the token extractor to get the new key but it still is showing as unavailable. I can see the vacuum in the Xiaomi app (iOS) and the IP address is correct. 

Is there a command-line tool to send a command to the vacuum using the token that can give me more debugging options than just using HA?

**Comment by nickdos** [comment]
Solved my issue in the end - I was using the wrong country server - it was not the one associated with my other Xiaomi  devices, which I'd assume it was.

**Comment by PiotrMachowski** [comment]
The easiest way is to run tokens extractor and check if tokens are the same
