### ISSUE TITLE
Script runs and closes instantly with errors

### ISSUE THREAD

**Issue by omerbitas** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#18]
Hello
I'm running the script on windows as token_extractor.exe
When prompted, I type in my username, password, server.
when I click enter, the window prints something and closes within half a second.

Am I doing something wrong?
Thanks,

**Comment by omerbitas** [comment]
I was able to use a screen recorded and retrieve these errors:
![2021-02-21_16-30-40](https://user-images.githubusercontent.com/49685964/108628221-6086dc00-7462-11eb-9031-8ef9483d298f.png)

**Comment by omerbitas** [comment]
Tried on a non-workplace computer and worked. guess it had to do with some kind of certificate installed on that machine.

**Comment by PiotrMachowski** [comment]
Thank you for info!

**Comment by thundergreen** [comment]
I have same issue. CMD window in windows closes immediately after entering country code. imossible to copy the tokens :P Using windows 10

**Comment by PiotrMachowski** [comment]
@thundergreen you can try starting it from cmd, you should be able to get some output

**Comment by thundergreen** [comment]
, works but I somehow blocked all traffic to mi.com so no issue with your
app but my firewall/adguard settings .thanks a lot

Piotr Machowski <notifications@github.com> schrieb am Fr., 26. Feb. 2021,
15:06:
