### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Tragyn** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#22]
Running the token extractor I get this error:

> Logging in...
> Invalid login or password.
> Unable to log in. 

I've verified my credentials are accurate. I've tried the extractor on multiple computers and I get the same result.

Is this still working?

**Comment by PiotrMachowski** [comment]
Yes, it works.

Make sure you use Xiaomi cloud credentials (not ones to Roborock app) and disable any ads filtering software on your network (like AdGuard or PiHole)

**Comment by Tragyn** [comment]
> Yes, it works.
> 
> Make sure you use Xiaomi cloud credentials (not ones to Roborock app) and disable any ads filtering software on your network (like AdGuard or PiHole)

Thanks for the reply. I disabled my network adblockers, cleared DNS cache, and even tried over a mobile network, and I still get the same response. I've again verified that I'm using my Xiaomi cloud credentials. Is there any way I can troubleshoot this further?

**Comment by PiotrMachowski** [comment]
You can try to login using Xiaomi cloud account ID (you can see it in "Profile" section in Xiaomi Home app)

**Comment by Tragyn** [comment]
I've tried that as well, still no luck. I assume I must be doing something
wrong here, but I can't figure it out. I've logged in/out of my account on
both the website and the app just to be sure I've got the right
credentials.

**Comment by jun4rui** [comment]
Hello i have this problem too

**Comment by philipyoungg** [comment]
Have the same issue too with Python.

**Comment by philipyoungg** [comment]
Removing cloudflare DNS fixed it!

**Comment by PiotrMachowski** [comment]
@philipyoungg nice finding!
@Tragyn @jun4rui is this fix applicable in your case?

**Comment by PiotrMachowski** [comment]
@Tragyn @jun4rui I have added 2FA request handling, have it fixed this issue?

**Comment by GuillaumeCailloux** [comment]
Hello @PiotrMachowski ! Thank you for your work :). I still face the same issue as the guys before. When I tried to connect, I've got the url for 2step verification (event if I didn't activate this on my xiaomi account), I can click on it, the page display "ok", but still have the same thing after re-run the code...
It says "wrong creds", but I'm sure their right (and when it's not, i don't have the 2 steps verif url)
 
<img width="216" alt="Capture d’écran 2021-06-20 à 09 07 39" src="https://user-images.githubusercontent.com/66321621/122665401-4d351480-d1a7-11eb-87ee-b58b84e44ebf.png">

**Comment by PiotrMachowski** [comment]
@GuillaumeCailloux 2FA link must be opened on the device that has the same public IP address as machine that runs extractor. Is it possible that in your case IPs were different?

**Comment by GuillaumeCailloux** [comment]
@PiotrMachowski sorry for the noob comment ;) yeah it works great now, thank you very much !

**Comment by PiotrMachowski** [comment]
@GuillaumeCailloux that's great! Thank you for your feedback. I also have remove "invalid login or password" section when 2FA request appears

**Comment by pc-bastler** [comment]
> Yes, it works.
> 
> Make sure you use Xiaomi cloud credentials (not ones to Roborock app) and disable any ads filtering software on your network (like AdGuard or PiHole)

Could you please help me out here:

How do I connect my device, which I am using with the Roborock App to a cloud account?

I found no possibility except resetting it (and so loosing the configuration) :(

**Comment by PiotrMachowski** [comment]
@pc-bastler unfortunately that's the only way to connect it to Xiaomi cloud

**Comment by AlekBarta** [comment]
Hi, yesterday and today I'm trying to extract the token. I am unable to connect with the same error you have addressed here. I am using extractor and 2FA on the same pc (same IP) - login failed. Is there any new version of Xiaomi API? Thanks

**Comment by Orsonorix** [comment]
I have same problem with login, credentials and region are correct. I can login to cloud in browser but no luck in token extractor. I've tried using mobile hotspot but no luck. Any suggestions? Thanks

**Comment by jksmurf** [comment]
Me too. I have the same problem with login. Credentials and region are correct.

**Comment by elisa-san** [comment]
I had tons of problems logging in, but succeedeed. 
Make sure you have the latest version that asks captcha.
Most captchas seemed impossible and I got it wrong maybe dozen times.
If the program tells you to open link, open link.
Good luck
