### ISSUE TITLE
adding a device that has been added via the roborock app to the xiaomi account?

### ISSUE THREAD

**Issue by jamiekris** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#24]
I have setup my vacuum via the roborock app and this script seems only designed for the Mi home account. Is there a way to migrate the device from the roborock app to the Mi home account? Can you please help in getting this done, or is it a whole new setup from scratch?

I do not have a Xiaomi gateway that controls all devices at home. So not sure how the account there should work. Is there a similar script for the roborock app?

**Comment by PiotrMachowski** [comment]
I don't know if there is a similar tool for Roborock app (as far as I know it uses Tuya cloud). You don't need to have Xiaomi gateway to use Xiaomi Home app. To migrate your vacuum you have to reset it.

Related discussion: #9

**Comment by jamiekris** [comment]
Do you know if I will loose the saved maps when I reset the vacuum? Or will the maps and the zones marked in them can be re-synced if I reconnect the vacuum to the roborock app again?

**Comment by PiotrMachowski** [comment]
I think so, but I'm not sure, I've never done it

**Comment by jamiekris** [comment]
Thanks. I'll try it out and post back.

**Comment by jLynx** [comment]
Any update @jamiekris ?

**Comment by jamiekris** [comment]
Sorry I stalled on this idea and never tried it out. Will try to give it a shot over the coming weekend possibly.
