### ISSUE TITLE
Can it be used for MiBand 4 token extraction?

### ISSUE THREAD

**Issue by Fazel94** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#3]
Can this script be used for MiBand 4 Bluetooth token extraction?

**Comment by PiotrMachowski** [comment]
I don't know, because I don't have it. You have to try it by yourself

**Comment by PiotrMachowski** [comment]
Please leave comment if it worked for you

**Comment by Fazel94** [comment]
I logged into my MiFit app using MiCloud account but it doesn't show up on the devices.
