### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by provanguard** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#38]
I was able to log in and check all the servers, but no devices are being found.
I have Roborock S6 MaxV. I use the Roborock android app, which show a region in my user details, which is Denmark.

**Comment by PiotrMachowski** [comment]
Roborock app doesn't use Xiaomi cloud, but (as far as I remember) Tuya cloud

**Comment by provanguard** [comment]
The reason I ended up making this issue request is because I am trying to connect to my Roborock from Homey Pro. There is an "app" on Homey that is supposed to do it and they ask to provide Xiaomi token. In their guide, they link to your tool for extracting the token:

https://community.athom.com/t/app-roborock-vacuum-cleaners/49521/3

Did I miss something? How to get that token, if not with this tool?

**Comment by PiotrMachowski** [comment]
I was not able to check source code of this integration, but I have checked some post on this forum and it mentions Xiaomi app, so I think you have to migrate to Xiaomi Home app to use it.
