### ISSUE TITLE
Does it work with Xiaomi IR Remote?

### ISSUE THREAD

**Issue by faaafo** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#4]
Thank you for writing that tool :pray: 

P.S. I spent hours with an ipad, windows+itunes on a virtual machine (linux) to get the token. Hence my hesitation on just trying it out.

**Comment by PiotrMachowski** [comment]
It should, if it's available in Xiaomi Home. 

For Windows I suggest to use exe version, it doesn't require installation

**Comment by PiotrMachowski** [comment]
Please leave comment if it worked for you
