### ISSUE TITLE
Can't extract token

### ISSUE THREAD

**Issue by Fannangir** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#42]
Hi,
Following entering a username and password, I receive a message which says:
Logging in...
Two factor authentication required, please use following url and restart extractor:
And then comes the link.
And then says:
Invalid login or password.
Unable to log in.

Press ENTER to finish

I enter the link, verification process ends up with an ok message in the browser.

I run the extractor again, and can see the same loop, again asks to enter the url.
I have tried again, browser says again ok, but still, same messages from the extractor.

What I could be missing?

Thanks.

**Comment by malinduta** [comment]
Same here

**Comment by eduardstula** [comment]
I have the same problem

**Comment by Basti189** [comment]
Same here for Germany

No devices found for server "cn".
Unable to get devices.
No devices found for server "us".
No devices found for server "ru".
No devices found for server "tw".
No devices found for server "sg".
No devices found for server "in".
No devices found for server "i2".

Press ENTER to finish

**Comment by piposhub** [comment]
Unable to retrieve token from any server. Same as above. Mi home app works without issues. Also home assistant miio integration has issues.

**Comment by GileanEU** [comment]
Same here, it logs in but returns "Unable to get devices" on a server where my devices are.

**Comment by peterhoe** [comment]
> Unable to retrieve token from any server. Same as above. Mi home app works without issues. Also home assistant miio integration has issues.

Looks like Xiaomi are having some problems with their server / cloud infrastructure

https://www.reddit.com/r/Xiaomi/comments/rsrwtk/eu_servers_31122022_not_working/

**Comment by canedje** [comment]
same here
![image](https://user-images.githubusercontent.com/23150947/147851006-22b7a401-59c2-4817-8917-da5f606b37e6.png)

**Comment by tonka3000** [comment]
I have the same problem since yesterday. I already extracted the token and use it for 2 weeks. Now the token seems to be invalid and extracting a new one does not work with the error no device found.

**Comment by qweluke** [comment]
I'm having the same error :/

**Comment by achisto** [comment]
Same error here. It also doesn't work with [this other solution](https://github.com/Maxmudjon/Get_MiHome_devices_token/releases) so it seems, like Xiaomi changed something on their side.

**Comment by konradcolle** [comment]
I have just checked now, the token extractor works again!

**Comment by GileanEU** [comment]
Confirmed, works for me as well! :)

**Comment by bartocc** [comment]
I just tried, but it still fails on my side

```
➜ python3 token_extractor.py      
Username (email or user ID):
foo
Password:
bar
Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:

Logging in...
Invalid login or password.
Unable to log in.

Press ENTER to finish
```

**Comment by PiotrMachowski** [comment]
@bartocc do you use Xiaomi Home credentials or e.g. ones from Roborock app?

**Comment by bartocc** [comment]
> Roborock app

> @bartocc do you use Xiaomi Home credentials or e.g. ones from Roborock app?

Roborock app

**Comment by PiotrMachowski** [comment]
@bartocc Roborock app doesn't use Xiaomi account

**Comment by bartocc** [comment]
> @bartocc Roborock app doesn't use Xiaomi account

Ok, I did not realize two different accounts existed…

I guess I need to setup the Xiaomi home app, add to roborock inside this app and then get the token, right?

**Comment by PiotrMachowski** [comment]
Exactly

**Comment by Thijske1995** [comment]
I cannot enter the password. With all other data I can enter my data, but I cannot enter the password. Does this look familiar to you?

**Comment by PiotrMachowski** [comment]
Password is entered, it's just invisible

**Comment by Thijske1995** [comment]
Thanks!

**Comment by swissMack** [comment]
Won't allow me to log in, tried from the *.exe file and from homeassistant,
I made sure user/pass was correct from Xiaomi app and reset password to suit, 
I tried with my user ID and email id, added password when prompted and tried with bot de and blank for server options

pasted below is the response 
-----------------------

Password:

Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:


Logging in...
Invalid login or password.
Unable to log in.

Press ENTER to finish

**Comment by andreasgraf42** [comment]
same issue here as @swissMack with the extractor, HA Integration response "Authentication Error: Invalid password."
but credentials are correct. also tried all the tricks with being logged in with browser on the same time/device using extractor. did not help.
any ideas?

**Comment by RoDeP0** [comment]
Same here. "Invalid login or password". I know the credentials are correct. Already deleted my Xiaomi account and signed up for a new one, just to make sure. Same result. Not using the Roborock account. The devices (two LYWSD03MMC temp sensors) are working in the Xiaomi Home app.

**Comment by PiotrMachowski** [comment]
@RoDeP0 do you use the latest version of the tokens extractor? If so, does it request 2FA code?

**Comment by PiotrMachowski** [comment]
> Then it found my device...on the "de" server.

🤯

**Comment by andreasgraf42** [comment]
Latest version worked perfect for me. Thanks @PiotrMachowski

**Comment by MasterDave2001** [comment]
I'm getting the following error when trying to connect: Mi Token must be 12 hex digits!

The token from the tokens extractor is 24 hex characters.

**Comment by LukeWhaskavsky** [comment]
Hi,
It doesn't work for me. Every time I get:
```
Two factor authentication required, please use following url and restart extractor:
https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=...

Invalid login or password.
Unable to log in.

Press ENTER to finish
```
Nothing helps.

**Comment by PiotrMachowski** [comment]
@LukeWhaskavsky  #43
