### ISSUE TITLE
QUESTION - Support for Roborock "cloud"

### ISSUE THREAD

**Issue by anthraxn8b** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#45]
Hi!
I tried to avoid to use the xiaomi cloud - now I have to stick to the roborock "cloud"...
Is it also possible to read out that token?
THX in advance!

**Comment by PiotrMachowski** [comment]
As far as I know Roborock app uses completely different servers, so it requires a dedicated app.

BTW, is it possible to use vacuum that is connected to Roborock app in HA?
