### ISSUE TITLE
Shared home

### ISSUE THREAD

**Issue by barbierp35** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#46]
Hi,

I created an account "Home Assistant" in Xiaomi Home not to use my personal account and don't write my personal password in secrets.yaml of my Home Assistant. With my personal Xiaomi Home account, I share my home to "Home Assistant" account with admin access.

With this "Xiaomi-cloud-tokens-extractor", I can get my vacuum informations when I use my personnal account, but not when I use the "Home Assistant" account. Certainly because it's not my home in "Home assistant" account, but it's a shared home ?

In the "xiaomi_cloud_map_extractor" of the configuration.yaml, I tested to set token I recovered with my personnal account and the xiaomi username and password of my "Home assistant account", but vacuum informations don't go up.

Have you a fix please ?

**Comment by PiotrMachowski** [comment]
Unfortunately both token extractor and map extractor uses API calls that can only be executed by device owner

**Comment by barbierp35** [comment]
Okay, thank you for your response and thanks for your code 👍
