### ISSUE TITLE
xiaomi servers don't find my device

### ISSUE THREAD

**Issue by MichaelKentBurns** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#48]
I bought my roborock on amazon.
I installed the iOS app on my phone and iPad and can configure rooms, maps.   All is well.

Now, I just installed a non hoobs box and set it up. 
I have installed this plugin into my hoobs box. 
When trying to use token_extractor it says: 

```
Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:


Logging in...
Logged in.

No devices found for server "cn".
No devices found for server "de".
No devices found for server "us".
No devices found for server "ru".
No devices found for server "tw".
No devices found for server "sg".
No devices found for server "in".
No devices found for server "i2".

Press ENTER to finish
```

I expect this is happening because I setup my vacuum using it's app, but I had not yet created a xiaomi user account.   Now I have that account, but it's not finding my device.  

Clues as to how to fix this?

**Comment by PiotrMachowski** [comment]
Which app do you use? Vacuum had to be added in Xiaomi Home for Tokens Extractor to work

**Comment by MichaelKentBurns** [comment]
I use the recommended app called Roborock

Where shall I find instructions for registering my vacuum to Xiaomi Home?

**Comment by PiotrMachowski** [comment]
Roborock app uses different cloud, so it won't work with Extractor.

To add your vacuum to Xiaomi Home you have to reset it.

**Comment by MichaelKentBurns** [comment]
Is there a different app I can use that will register it correctly? 
If I reset it I will loose all of my rooms.  
How will I be able to reprogram my rooms?

**Comment by PiotrMachowski** [comment]
Nope, only Xiaomi Home. You will have to reprogram them in Xiaomi Home.

**Comment by austinarchibald** [comment]
Darn. Is there any homebridge plugin if you use the roborock app, not the Xiaomi Home app? I don't want to remove from Roborock. I like the app.
