### ISSUE TITLE
Aqara home

### ISSUE THREAD

**Issue by kaizer666** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#55]
My hub m1s is in Aqara home. How to extract token?

**Comment by PiotrMachowski** [comment]
Does Aquara home use Xiaomi account?

**Comment by kaizer666** [comment]
Yes, MiHome and aqara home use one email for auth in app

**Comment by PiotrMachowski** [comment]
You can try run extractor with your credentials, please let me know if it works

**Comment by kaizer666** [comment]
No, extractor find only mihome devices

**Comment by PiotrMachowski** [comment]
Ok, so it seems to use some other place to store devices
