### ISSUE TITLE
Oh, no. Just unpacked my Roborock S7 and need the token for HA.

### ISSUE THREAD

**Issue by digitalit** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#59]
i get the same error as the issue named only error. #58 

please forgive me if i post an issue wrongly.

Have a nice day

**Comment by PiotrMachowski** [comment]
Solutions described in #58

**Comment by digitalit** [comment]
@PiotrMachowski you are my hero!

Followed the manual guide on a Ubuntu server and voila. It worked.

Thank you so much!
