### ISSUE TITLE
Invalid Login or Password Always Returned - Information Correct in RoboRock.app

### ISSUE THREAD

**Issue by BillyFKidney** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#67]
I have attempted using my email address or Account ID (found on the profile page of the RoboRock.app) with my password but constant receive and error stating invalid login:

![image](https://user-images.githubusercontent.com/65253277/167505120-1b1f3344-f8df-4d7e-9787-c44af7fac372.png)
I've changed my password, logged in and out of the Roborock.app with no issues.

![image](https://user-images.githubusercontent.com/65253277/167505250-228cbc57-2986-4dbe-af87-1df8d3d7fd9a.png)
![image](https://user-images.githubusercontent.com/65253277/167505347-c7fd839c-796f-4e4d-9d4a-90a3122f176e.png)
Providing a country code of us doesn't affect the output.

**Comment by BillyFKidney** [comment]
Re-read the instructions and I am using the wrong app on my iPhone *DOH*

**Comment by PiotrMachowski** [comment]
¯\\\_( ͡° ͜ʖ ͡°)\_/¯
