### ISSUE TITLE
Unable to add xiaomi robot vacuum cleaner dreame.vacuum.mc1808

### ISSUE THREAD

**Issue by VegardBF** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#68]
Hi Im not able to add robot vacuum cleaner type dreame.vacuum.mc1808. I found the tokens and IP but the message i get from xiaomi app in homey app is "device.getState is not a function". Please help. It worked wit my S5 modell.

**Comment by PiotrMachowski** [comment]
It seems like a problem with Xiaomi app in Homey, not Tokens Extractor
