### ISSUE TITLE
Can not run Token extractor on my computer

### ISSUE THREAD

**Issue by DZ8888** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#69]
I ran Token extractor file in my computer (win10) but got error message said this APP cannot run on this computer with remark 
said I should contact with APP provider to get suitable version. Does it mean there is another version I should use?
or I  make any mistake? 
Please help me for fix this problem. Thanks!

**Comment by PiotrMachowski** [comment]
Could you provide some details about your computer?

**Comment by DZ8888** [comment]
Are following information enough?
or what I should provide more? Thanks!

CPU: Intel(R) Core(TM)2 Quad  CPU   Q8200  @ 2.33GHz   2.34 GHz
RAM : 4.00 GB (3.00 GB available)
OS: Win 10 proffessional; version : 21H2

**Comment by DZ8888** [comment]
BTW, I also try to run it in SSH & web terminal but fail too.
the error message is as below. 
![Token error](https://user-images.githubusercontent.com/59321522/173212381-664c0ec6-8679-4994-96f4-686f10138e5f.png)

**Comment by PiotrMachowski** [comment]
Is your Windows installation 64bit?

You have used wrong SSH addon, Tokens Extractor can't be run in the official one, you have to use one from community addons

**Comment by DZ8888** [comment]
My Windows is 32bit. is it the problem?
I will get the SSH from community addons and try it again. Thanks a lot!

**Comment by DZ8888** [comment]
I tried the SSH from community addons with protect mode off. it works. I can see all device's token now. Thanks!
BTW, sorry for one more question, how can I copy the text out from SSH? Thanks a lot!

**Comment by PiotrMachowski** [comment]
> My Windows is 32bit. is it the problem?

Yessss, I think that's the problem



> how can I copy the text out from SSH

With `[Ctrl]` + `[Shift]` + `[C]` as far as I remember

**Comment by DZ8888** [comment]
Got it! Thank you!

從我的iPhone傳送
