### ISSUE TITLE
Indian Server?

### ISSUE THREAD

**Issue by sheminasalam** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#7]
Hi is there anyway to get this info from Indian server?

**Comment by PiotrMachowski** [comment]
Have you tried the other ones?

**Comment by sheminasalam** [comment]
I tried to get the device linked to other servers but it is not happening.the device is not detected in the app when I select a different region.

**Comment by PiotrMachowski** [comment]
Try using extractor without providing a server, it will check all available ones

**Comment by sheminasalam** [comment]
i have tried.. i get this message
```
No devices found for country "cn".
No devices found for country "de".
No devices found for country "us".
No devices found for country "ru".
No devices found for country "tw".
No devices found for country "sg".
```

**Comment by PiotrMachowski** [comment]
I have added Indian server, please check out the latest version
