### ISSUE TITLE
Unable to get devices from server

### ISSUE THREAD

**Issue by NunopRolo** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#70]
Hi,
I followed these steps for login (https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/43#issuecomment-1186615161) but the answer is "Unable to get devices from server " for all servers it looks for. The region that appears on the xiaomi account is Germany. Does anyone know what it could be?
Thanks

**Comment by PiotrMachowski** [comment]
Do you use shared devices?

**Comment by NunopRolo** [comment]
> Do you use shared devices?

No

**Comment by PiotrMachowski** [comment]
Do you use any kind of network traffic filtering tool?

**Comment by NunopRolo** [comment]
> Do you use any kind of network traffic filtering tool?

Neither. But in the meantime I noticed a strange thing, that when I enter the xiaomi account through the browser, in the "Manage devices" button it appears that there are no devices yet. But with the same account in the google home application on the mobile phone, the configured lamp appears.
Maybe it's a problem with my xiaomi account, I'm sorry.
Thank you

**Comment by PiotrMachowski** [comment]
Are they visible in Xiaomi Home?

**Comment by NunopRolo** [comment]
> Are they visible in Xiaomi Home?

Yes:
![Screenshot_2022-07-25-10-09-05-66_89ed83f5c7ca8fa2c91fc75c50289338](https://user-images.githubusercontent.com/56121280/180741751-3fe19211-1c0f-4423-9af2-a23ce3d4182e.jpeg)
.

**Comment by NunopRolo** [comment]
I created a new account and associated the lamp there, and now it works. Thanks!
