### ISSUE TITLE
Cannot find or open token extractor

### ISSUE THREAD

**Issue by pickett** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#77]
Running your token extractor just now from Home Assistant terminal. This worked a few days ago on the same setup but running the provided curl provides an error now

“Cannot find or open token_extractor.zip, token_extractor.zip.zip or token_extractor.zip.ZIP”

I will attempt to hit an earlier commit to see if this is a regression or just my local instance changing.

**Comment by Beeez** [comment]
@pickett Looks like 5 days ago they updated run.sh to use curl, and accidentally pasted in the token_extractor_docker download instead of the token_extractor.zip

**Comment by PiotrMachowski** [comment]
@Beeez you are right, I have missed that typo in PR. I have fixed the code.

**Comment by pickett** [comment]
Thank you!
