### ISSUE TITLE
BLE Key shows all FF but this doesn't appear to be the actual key

### ISSUE THREAD

**Issue by dasrue** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#79]
Here is the output for the device I'm interested in:
```Devices found for server "sg":
   ---------
   NAME:     Door and window sensor
   ID:       blt.1.1a8g8higl4c00
   BLE KEY:  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
   MAC:      E4:AA:EC:53:BC:55
   TOKEN:    dda6e4313a0cb6efdf4da9b0
   MODEL:    isa.magnet.dw2hl
   ---------
```
In fact, all the devices on my account show all FF in the BLE key. When trying to decode the packets using all FF as the key it doesn't work, which suggests to me this device has a proper key. I wonder if Xiaomi have changed something recently that would break this script?

**Comment by PiotrMachowski** [comment]
Was it working for your devices before?

**Comment by dasrue** [comment]
I think it did work in the past, but I deleted and then re added the device to my mi home app, and now it shows up the key as expected.
