### ISSUE TITLE
The device model is not known, not able to set up the device using config flow

### ISSUE THREAD

**Issue by Thijske1995** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#87]
Hi, 

I get the message The device model is not known, not able to set up the device using config flow. 
Does anyone know how I can fix this?

**Comment by PiotrMachowski** [comment]
This is not a problem with this tool, I assume you have tried to integrate a device that is not supported by HA at this moment. You can create an issue in [HA core](https://github.com/home-assistant/core/) and use a different integration as a temporary solution
