### ISSUE TITLE
Unable to extract ble key for Xiaomi Door Lock 1S (XMZNMS08LM)

### ISSUE THREAD

**Issue by tianzhuang55** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#88]
The lock device is well paired in Mi Home App, and connected to Xiaomi Multimode Gateway. After running the extractor, a list of devices information was returned including the lock(XMZNMS08LM), however I could only find the token(24digits) instead of the ble key(32digits)

**Comment by PiotrMachowski** [comment]
I don't think it's possible:
https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/57
