### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by realjax** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#94]
error after chosing server is:

AttributeError: function/symbol 'ARC4_stream_init' not found in library '/usr/local/lib/python3.7/site-packages/Crypto/Util/../Cipher/_ARC4.cpython-37m-darwin.so': dlsym(0x308cb4fd0, ARC4_stream_init): symbol not found

**Comment by realjax** [comment]
this fixed it 👍 

pip install pycryptodome==3.0.0

**Comment by PiotrMachowski** [comment]
Have you run the following command?
```
pip3 install -r requirements.txt
```

**Comment by pwaldon** [comment]
Python 3.12.3, works with `pycryptodome==3.19.0`
