### ISSUE TITLE
Is this still workin

### ISSUE THREAD

**Issue by tolwan** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#97]
Hi Piotr , 
Is this still working , i get every time wrong email or Password 
I have a S7 Ultra Max 

Thanks in advance 
Tolwan

**Comment by PiotrMachowski** [comment]
Yes, it should work. Do you use Xiaomi Home or Roborock app?

**Comment by tolwan** [comment]
Roborock app

**Comment by PiotrMachowski** [comment]
Roborock app doesn't work with this tool
